version: "3.9"
# network
networks:
  tnet:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.99.0/24"

x-common-fields: &common-fields
  stdin_open: true
  tty: true
  networks:
    - tnet
  security_opt:
    - no-new-privileges:true
  restart: always

# nginx proxy manager, frontend and backend services
services:
  npm:
    <<: *common-fields
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  frontend:
    <<: *common-fields
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    env_file:
      - ./frontend/.env

  backend:
    <<: *common-fields
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ${ENTITY_LIST}:/app/entity_list.xlsx
      - ${TEMPLATE_PATH}/EAMS:/app/eams_template_out
      - ${TEMPLATE_PATH}/PFML:/app/med_template_out
      - ${TEMPLATE_PATH}/W2:/app/w2_template_out
      - ${TEMPLATE_PATH}/EFW2:/app/efw2_template_out